name: Deploy Remotely
on:
  push:
    branches: [main]

jobs:
  Deploy-Remotely:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - run: npm ci

      - name: Build for EC2
        run: NUXT_CONFIG=nuxt.config/ec2.ts npm run build

      - name: Transfer Build Folder to EC2 Instance
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
          REMOTE_USER: ${{ secrets.AWS_EC2_DEPLOY_USER }}
          REMOTE_PORT: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
          SOURCE: ".output/"
          TARGET: "/home/ubuntu/nuxt-to-aws/.output"


      # - name: Check and Install PM2 if Not Installed
      #   uses: appleboy/ssh-action@master
      #   with:
      #         key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
      #         host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
      #         username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
      #         port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
      #         script: |
      #           export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
      #           if ! command -v pm2 &> /dev/null
      #           then
      #             echo "PM2 not found. Installing PM2"
      #             npm install -g pm2
      #           else
      #             echo "PM2 is already installed"
      #           fi

      # - name: Restart PM2 process
      #   uses: appleboy/ssh-action@master
      #   with:
      #     key: ${{ secrets.AWS_EC2_DEPLOY_PEM_KEY }}
      #     host: ${{ secrets.AWS_EC2_DEPLOY_IP_ADDRESS_HOST }}
      #     username: ${{ secrets.AWS_EC2_DEPLOY_USER }}
      #     port: ${{ secrets.AWS_EC2_DEPLOY_PORT }}
      #     script: |
      #       export PATH=$PATH:/home/ubuntu/.nvm/version/node/v22.8.0/bin
      #       cd /home/ubuntu/vanas-nuxt-aws-git-actions/.output
      #       pm2 restart nux-app || pm2 start server/index.mjs --name "nuxt-app"
